FROM python:3.12.6-alpine3.20
LABEL authors="Vadim Sosnin"

WORKDIR /source
RUN mkdir ./requirements
COPY ../requirements.txt ./requirements/requirements.txt
RUN pip install -r ./requirements/requirements.txt
CMD ["python"]


